;PROGRAM COMPILED BY GREAT COW BASIC (0.98.<<>> 2019-05-14 (WINDOWS 32 BIT))
;NEED HELP? SEE THE GCBASIC FORUMS AT HTTP://SOURCEFORGE.NET/PROJECTS/GCBASIC/FORUMS,
;CHECK THE DOCUMENTATION OR EMAIL W_CHOLMONDELEY AT USERS DOT SOURCEFORGE DOT NET.

;********************************************************************************

;SET UP THE ASSEMBLER OPTIONS (CHIP TYPE, CLOCK SOURCE, OTHER BITS AND PIECES)
 LIST P=16F15355, R=DEC
#INCLUDE <P16F15355.INC>
 __CONFIG _CONFIG1, _CLKOUTEN_OFF & _RSTOSC_HFINT32 & _FEXTOSC_OFF
 __CONFIG _CONFIG2, _MCLRE_ON
 __CONFIG _CONFIG3, _WDTE_OFF
 __CONFIG _CONFIG4, _LVP_OFF
 __CONFIG _CONFIG5, _CP_OFF

;********************************************************************************

;SET ASIDE MEMORY LOCATIONS FOR VARIABLES
DELAYTEMP	EQU	112
MYBYTEVAR	EQU	32
MYBYTEVAR_H	EQU	33
SYSTEMP1	EQU	34
SYSWAITTEMPUS	EQU	117
SYSWAITTEMPUS_H	EQU	118

;********************************************************************************

;VECTORS
	ORG	0
	PAGESEL	BASPROGRAMSTART
	GOTO	BASPROGRAMSTART
	ORG	4
	RETFIE

;********************************************************************************

;START OF PROGRAM MEMORY PAGE 0
	ORG	5
BASPROGRAMSTART
;CALL INITIALISATION ROUTINES
	CALL	INITSYS

;START OF THE MAIN PROGRAM
;THIS HAS LOTS OF BANKSELS... HOW DO SET ERRORLEVEL -302
	BCF	TRISA,1
SYSDOLOOP_S1
	MOVLW	2
	MOVWF	DELAYTEMP
DELAYUS1
	DECFSZ	DELAYTEMP,F
	GOTO	DELAYUS1
	NOP
	CLRF	SYSTEMP1
	BTFSC	PORTA,1
	INCF	SYSTEMP1,F
	COMF	SYSTEMP1,F
	BCF	LATA,1
	BTFSC	SYSTEMP1,0
	BSF	LATA,1
	INCF	MYBYTEVAR,F
	BTFSC	STATUS,Z
	INCF	MYBYTEVAR_H,F
	GOTO	SYSDOLOOP_S1
SYSDOLOOP_E1
BASPROGRAMEND
	SLEEP
	GOTO	BASPROGRAMEND

;********************************************************************************

INITSYS
;OSCCON TYPE IS 100
	MOVLW	96
	BANKSEL	OSCCON1
	MOVWF	OSCCON1
	CLRF	OSCCON3
	CLRF	OSCEN
	CLRF	OSCTUNE
;THE MCU IS A CHIP FAMILY 15
;OSCCON TYPE IS 102
	MOVLW	6
	MOVWF	OSCFRQ
	BANKSEL	ADCON1
	BCF	ADCON1,ADFM
	BCF	ADCON0,ADON
	BANKSEL	ANSELA
	CLRF	ANSELA
	CLRF	ANSELB
	CLRF	ANSELC
	BANKSEL	CM2CON0
	BCF	CM2CON0,C2EN
	BCF	CM1CON0,C1EN
	BANKSEL	PORTA
	CLRF	PORTA
	CLRF	PORTB
	CLRF	PORTC
	CLRF	PORTE
	RETURN

;********************************************************************************

;START OF PROGRAM MEMORY PAGE 1
	ORG	2048
;START OF PROGRAM MEMORY PAGE 2
	ORG	4096
;START OF PROGRAM MEMORY PAGE 3
	ORG	6144

 END
