;PROGRAM COMPILED BY GREAT COW BASIC (0.98.<<>> 2019-05-14 (WINDOWS 32 BIT))
;NEED HELP? SEE THE GCBASIC FORUMS AT HTTP://SOURCEFORGE.NET/PROJECTS/GCBASIC/FORUMS,
;CHECK THE DOCUMENTATION OR EMAIL W_CHOLMONDELEY AT USERS DOT SOURCEFORGE DOT NET.

;********************************************************************************

;SET UP THE ASSEMBLER OPTIONS (CHIP TYPE, CLOCK SOURCE, OTHER BITS AND PIECES)
 LIST P=16F15355, R=DEC
#INCLUDE <P16F15355.INC>
 ERRORLEVEL -302
 __CONFIG _CONFIG1, _CLKOUTEN_OFF & _RSTOSC_HFINT32 & _FEXTOSC_OFF
 __CONFIG _CONFIG2, _MCLRE_ON
 __CONFIG _CONFIG3, _WDTE_OFF
 __CONFIG _CONFIG4, _LVP_OFF
 __CONFIG _CONFIG5, _CP_OFF

;********************************************************************************

;SET ASIDE MEMORY LOCATIONS FOR VARIABLES
DELAYTEMP EQU 112
DELAYTEMP2  EQU 113
MYBYTEVARIABLE  EQU 32
SYSSTRINGA  EQU 119
SYSWAITTEMPMS EQU 114
SYSWAITTEMPMS_H EQU 115

;********************************************************************************

;VECTORS
  ORG 0
  PAGESEL BASPROGRAMSTART
  GOTO  BASPROGRAMSTART
  ORG 4
  RETFIE

;********************************************************************************

;START OF PROGRAM MEMORY PAGE 0
  ORG 5
BASPROGRAMSTART
;CALL INITIALISATION ROUTINES
  CALL  INITSYS
;AUTOMATIC PIN DIRECTION SETTING
  CLRF  TRISA

;START OF THE MAIN PROGRAM
;TOO COMPLEX...
SYSDOLOOP_S1
  MOVLW 5
  MOVWF SYSWAITTEMPMS
  CLRF  SYSWAITTEMPMS_H
  CALL  DELAY_MS
  MOVF  MYBYTEVARIABLE,W
  MOVWF SYSSTRINGA
  CALL  GRAY_CODE
  MOVWF PORTA
  GOTO  SYSDOLOOP_S1
SYSDOLOOP_E1
BASPROGRAMEND
  SLEEP
  GOTO  BASPROGRAMEND

;********************************************************************************

DELAY_MS
  INCF  SYSWAITTEMPMS_H, F
DMS_START
  MOVLW 14
  MOVWF DELAYTEMP2
DMS_OUTER
  MOVLW 189
  MOVWF DELAYTEMP
DMS_INNER
  DECFSZ  DELAYTEMP, F
  GOTO  DMS_INNER
  DECFSZ  DELAYTEMP2, F
  GOTO  DMS_OUTER
  DECFSZ  SYSWAITTEMPMS, F
  GOTO  DMS_START
  DECFSZ  SYSWAITTEMPMS_H, F
  GOTO  DMS_START
  RETURN

;********************************************************************************

GRAY_CODE
  MOVLW 17
  SUBWF SYSSTRINGA, W
  BTFSC STATUS, C
  RETLW 0
  MOVF  SYSSTRINGA, W
  ADDLW LOW TABLEGRAY_CODE
  MOVWF SYSSTRINGA
  MOVLW (HIGH TABLEGRAY_CODE) & 127
  BTFSC STATUS, C
  ADDLW 1
  MOVWF PCLATH
  MOVF  SYSSTRINGA, W
  MOVWF PCL
TABLEGRAY_CODE
  RETLW 16
  RETLW 0
  RETLW 0
  RETLW 0
  RETLW 1
  RETLW 1
  RETLW 1
  RETLW 3
  RETLW 3
  RETLW 3
  RETLW 3
  RETLW 7
  RETLW 7
  RETLW 7
  RETLW 15
  RETLW 15
  RETLW 15

;********************************************************************************

INITSYS
;OSCCON TYPE IS 100
  MOVLW 96
  BANKSEL OSCCON1
  MOVWF OSCCON1
  CLRF  OSCCON3
  CLRF  OSCEN
  CLRF  OSCTUNE
;THE MCU IS A CHIP FAMILY 15
;OSCCON TYPE IS 102
  MOVLW 6
  MOVWF OSCFRQ
  BANKSEL ADCON1
  BCF ADCON1,ADFM
  BCF ADCON0,ADON
  BANKSEL ANSELA
  CLRF  ANSELA
  CLRF  ANSELB
  CLRF  ANSELC
  BANKSEL CM2CON0
  BCF CM2CON0,C2EN
  BCF CM1CON0,C1EN
  BANKSEL PORTA
  CLRF  PORTA
  CLRF  PORTB
  CLRF  PORTC
  CLRF  PORTE
  RETURN

;********************************************************************************

;START OF PROGRAM MEMORY PAGE 1
  ORG 2048
;START OF PROGRAM MEMORY PAGE 2
  ORG 4096
;START OF PROGRAM MEMORY PAGE 3
  ORG 6144

 END
